In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [2]:
def removeOutliers(dataFrame, zScoreTreshold):
    print(dataFrame.shape)
    numericalVariablesColumnsList = ["campaign_payout", "clicks", "conversions", "payout", "net", "TR.ROI", "EPC", "train_clicks"]
    z = np.abs(stats.zscore(dataFrame[numericalVariablesColumnsList]))
    dataFrame_o = dataFrame[(z < zScoreTreshold).all(axis=1)]
    print(dataFrame_o.shape)
    return dataFrame_o

In [3]:
data = pd.read_csv('train_data.csv')

In [5]:
data_optimised = removeOutliers(data,3)

(50781, 38)
(49070, 38)


In [6]:
X = data[['clicks','conversions','revenue','lp_clicks','cpc','cost','impressions','net','TR.ROI','EPC']]
y = data[['predictions_class']]

In [8]:
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn import metrics
from sklearn import tree
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import ADASYN
from imblearn.under_sampling import RandomUnderSampler

# labelencoder for y
le = preprocessing.LabelEncoder()
y = y.values.reshape(1,-1)[0]
y = le.fit_transform(y)


In [9]:
from sklearn.ensemble import RandomForestClassifier

In [10]:
a = ADASYN()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_res, y_res = X_train, y_train 
a.fit_resample(X_train, y_train)
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
model_crf = RandomForestClassifier()

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
model_crf.fit(X_res,y_res)

RandomForestClassifier()

In [14]:
y_pred = model_crf.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
confusion_matrix = confusion_matrix(y_test,y_pred)
print(confusion_matrix)

[[1206    0  131  398]
 [   2   61   25    2]
 [ 116    9 3654  460]
 [ 144    0  215 8812]]


In [17]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [18]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[1206    0  131  398]
 [   2   61   25    2]
 [ 116    9 3654  460]
 [ 144    0  215 8812]]
              precision    recall  f1-score   support

           0       0.82      0.70      0.75      1735
           1       0.87      0.68      0.76        90
           2       0.91      0.86      0.88      4239
           3       0.91      0.96      0.94      9171

    accuracy                           0.90     15235
   macro avg       0.88      0.80      0.83     15235
weighted avg       0.90      0.90      0.90     15235

0.9014112241549065
